config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyPostgresBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MyPostgreSQLBlog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', 
      :rel => 'apple-touch-icon-precomposed', 
      :skip_pipeline => true, 
      :type => 'image/png', 
      :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png',
      :rel => 'apple-touch-icon-precomposed', 
      :skip_pipeline => true, 
      :type => 'image/png', 
      :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', 
      :rel => 'apple-touch-icon-precomposed', 
      :skip_pipeline => true, 
      :type => 'image/png', 
      :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', 
      :rel => 'apple-touch-icon-precomposed', 
      :skip_pipeline => true,
      :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', 
      :skip_pipeline => true,
      :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <%= link_to image_tag("anynines.svg", alt: "anynines logo", height: '60'),
                    "/",
                    class: "navbar-brand" %>
      </div>
    </div>

    <div class="container content">
      <div class="row">
        <div class="col-lg-9">
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

    <div class="footer">
      <div class="container">
        <span>&copy; 2015 <a href="https://enterprise.anynines.com">anynines enterprise</a></span>
      </div>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => "form-horizontal post" } do |f| %>

    <% if @post.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, class: 'form-control', rows: 20 %>
    </div>
  </div>

  <br />
  <br />

  <%= f.submit %>

  <div class='actions rAlign'>
    <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                posts_path %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1>MyBlog</h1>

  <div class="actions rAlign">
    <%= link_to t('.new', :default => t("helpers.links.new")), new_post_path %>
  </div>
</div>
<div class="posts">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="title">
        <h2><%= link_to post.title, post_path(post) %></h2>
      </div>
      <div class="body">
        <p><%= simple_format truncate(post.body, length: 750) %></p>
      </div>

      <div class="post-footer">
        <span class="timestamps">
          Created at: <%=l post.created_at, format: :my_long %>,
          Updated at: <%=l post.updated_at, format: :my_long %>
        </span>
        <span class="actions">
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_post_path(post)  %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          post_path(post),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
        </span>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/posts/_form.html.erb
<%= form_for @post, :html => { :class => "form-horizontal post" } do |f| %>

    <% if @post.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@post[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, class: 'form-control', rows: 20 %>
    </div>
    <%= error_span(@post[:body]) %>
  </div>

  <br />
  <br />

  <%= f.submit %>

  <div class='actions rAlign'>
    <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                posts_path %>
  </div>

<% end %>

app/views/posts/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1>MyBlog</h1>

  <div class="actions rAlign">
    <%= link_to t('.new', :default => t("helpers.links.new")), new_post_path %>
  </div>
</div>
<div class="posts">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="title">
        <h2><%= link_to post.title, post_path(post) %></h2>
      </div>
      <div class="body">
        <p><%= simple_format truncate(post.body, length: 750) %></p>
      </div>

      <div class="post-footer">
        <span class="timestamps">
          Created at: <%=l post.created_at, format: :my_long %>,
          Updated at: <%=l post.updated_at, format: :my_long %>
        </span>
        <span class="actions">
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_post_path(post)  %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          post_path(post),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
        </span>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t @post.title %></h1>

  <div class="actions rAlign">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                posts_path %>
  </div>
</div>

<p>
  <%= simple_format @post.body %>
</p>

<div class="post-footer">
  <span class="timestamps">
    Created at: <%=l @post.created_at, format: :my_long %>,
    Updated at: <%=l @post.updated_at, format: :my_long %>
  </span>
  <span class="actions">
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_post_path(@post)  %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    post_path(@post),
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
  </span>
</div>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t @post.title %></h1>

  <div class="actions rAlign">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                posts_path %>
  </div>
</div>

<p>
  <%= simple_format @post.body %>
</p>

<div class="post-footer">
  <span class="timestamps">
    Created at: <%=l @post.created_at, format: :my_long %>,
    Updated at: <%=l @post.updated_at, format: :my_long %>
  </span>
  <span class="actions">
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_post_path(@post)  %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    post_path(@post),
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
  </span>
</div>